[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "mesa",
  "libGL",
  "libGLU",
  "libglvnd",
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --break-system-packages --user -r requirements.txt"
]

[phases.start]
cmd = '''
export LD_LIBRARY_PATH=$(nix eval --raw nixpkgs.lib.makeLibraryPath [ libGL mesa libglvnd libGLU ]):$LD_LIBRARY_PATH && \
$HOME/.local/bin/gunicorn app:app --bind 0.0.0.0:$PORT
'''
